/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.util.Optional;
import javax.swing.JOptionPane;
import jokerstats.opap.OpapApiHandler;
import jokerstats.opap.statistics.JokerStatistics;
import org.jfree.ui.RefineryUtilities;

public class statisticsView extends javax.swing.JFrame {

    private JokerStatistics stats;
    
    /**
     * Creates new form statisticsView
     */
    public statisticsView() {
        
        // Λαμβάνονται τα στατιστικα απο το API του ΟΠΑΠ
        Optional<JokerStatistics> jokerStats = OpapApiHandler.getJokerStatistics();
        
        // Εαν η λήψη ηταν επιτυχής εμφανίζονται στον χρήστη
        if(jokerStats.isPresent())
               stats = jokerStats.get();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backToMainBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        simpleNumbersTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        bonusNumbersTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        printPdfBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ΣΤΑΤΙΣΤΙΚΑ");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ΣΤΑΤΙΣΤΙΚΑ ΠΑΙΧΝΙΔΙΟΥ ΤΖΟΚΕΡ ");

        backToMainBtn.setBackground(new java.awt.Color(255, 0, 0));
        backToMainBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        backToMainBtn.setText("↩ ΑΡΧΙΚΗ");
        backToMainBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMainBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Από ["+stats.getHeader().getLocalDateFrom()+"] μέχρι και ["+stats.getHeader().getLocalDateTo()+"]");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Σύνολο παιχνιδιών ΤΖΟΚΕΡ: ["+stats.getHeader().getDrawCount()+"]");

        simpleNumbersTable.setModel(stats.numbersTableModel());
        simpleNumbersTable.setEnabled(false);
        jScrollPane1.setViewportView(simpleNumbersTable);

        bonusNumbersTable.setModel(stats.bonusNumbersTableModel());
        bonusNumbersTable.setEnabled(false);
        jScrollPane2.setViewportView(bonusNumbersTable);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ΝΟΥΜΕΡΑ ΚΑΝΟΝΙΚΗΣ ΣΕΙΡΑΣ");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ΝΟΥΜΕΡΑ ΜΠΟΝΟΥΣ ΣΕΙΡΑΣ");

        printPdfBtn.setBackground(new java.awt.Color(0, 102, 102));
        printPdfBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        printPdfBtn.setText("ΕΚΤΥΠΩΣΗ PDF");
        printPdfBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printPdfBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backToMainBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printPdfBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backToMainBtn)
                    .addComponent(printPdfBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        backToMainBtn.getAccessibleContext().setAccessibleName("backToMainBtn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Event handler για την περίπτωση που 
     * ο χρήστης κανει κλικ στο κουμπί "< ΑΡΧΙΚΗ".
     * Κλείνει το τρέχον παράθυρο και εμφανίζει στον χρήστη την αρχική οθόνη.
     */
    private void backToMainBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMainBtnMouseClicked
        
        firstscreen startscreen = new firstscreen();
        RefineryUtilities.centerFrameOnScreen(startscreen);
        
        setVisible(false);
        dispose();
        
        startscreen.setVisible(true);
    }//GEN-LAST:event_backToMainBtnMouseClicked

    
    /**
     * Event handler για την περίπτωση που 
     * ο χρήστης κανει κλικ στο κουμπί "Εκτυπωση pdf".
     * Εμφανίζεται ενα μηνυμα επαληθευσης στον χρηστη και 
     * αν το αποδεχθεί δημιουργείται αρχειο pdf και 
     * σε περίπτωση αποτυχίας εμφανίζεται αντιστοιχο μηνυμα.
     */
    private void printPdfBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printPdfBtnMouseClicked
        
        if(stats.generatePDF())
            JOptionPane.showMessageDialog(this, "ΕΠΙΤΥΧΗΣ ΕΚΤΥΠΩΣΗ ΑΡΧΕΙΟΥ PDF!");
        else
            JOptionPane.showMessageDialog(this, "ΑΠΟΤΥΧΙΑ ΕΚΤΥΠΩΣΗΣ PDF...");
        
    }//GEN-LAST:event_printPdfBtnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainBtn;
    private javax.swing.JTable bonusNumbersTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton printPdfBtn;
    private javax.swing.JTable simpleNumbersTable;
    // End of variables declaration//GEN-END:variables
}
