/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.time.Month;
import java.util.Optional;
import javax.swing.JOptionPane;

import jokerstats.opap.MonthlyStats;
import jokerstats.opap.OpapApiHandler;

import org.jfree.ui.RefineryUtilities;

public class viewData extends javax.swing.JFrame {

    /**
     * Creates new form viewData
     */
    public viewData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yearForMonthlyStats = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        viewMonthlyStatsBtn = new javax.swing.JButton();
        backToMainBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TZOKER Select Monthly stats");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Έτος:");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Επιλέξτε χρονική περίοδο:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Μήνας:");

        yearForMonthlyStats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Μηνιαία Στατιστικά");

        viewMonthlyStatsBtn.setBackground(new java.awt.Color(0, 102, 255));
        viewMonthlyStatsBtn.setText("Προβολή");
        viewMonthlyStatsBtn.setToolTipText("");
        viewMonthlyStatsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMonthlyStatsBtnMouseClicked(evt);
            }
        });

        backToMainBtn.setBackground(new java.awt.Color(204, 0, 0));
        backToMainBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        backToMainBtn.setText("↩ ΑΡΧΙΚΗ");
        backToMainBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMainBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewMonthlyStatsBtn))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(yearForMonthlyStats, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backToMainBtn))
                        .addGap(0, 245, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backToMainBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(yearForMonthlyStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewMonthlyStatsBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewMonthlyStatsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMonthlyStatsBtnMouseClicked

        // Ετος που επέλεξε ο χρήστης
        int year    = Integer.parseInt(yearForMonthlyStats.getSelectedItem().toString());  
        
        // Μήνας που επέλεξε ο χρήστης
        Month month = Month.valueOf(monthComboBox.getSelectedItem().toString());
        
        // Λήψη στατιστικών για το μηνα month του ετους year, απο το API του ΟΠΑΠ
        Optional<MonthlyStats> stats = OpapApiHandler.getStatsForMonth(year, month);
        
        // Εαν η λήψη ηταν επιτυχής
        if (stats.isPresent()) {
            
            // Ο χρήστης οδηγείται σε νέα οθόνη για την προβολή των δεδομένων
            viewMonthlyStats statScreen = new viewMonthlyStats(year, month, stats.get());
            RefineryUtilities.centerFrameOnScreen(statScreen);

            setVisible(false);
            dispose();

            statScreen.setVisible(true);
        } 
        else // Διαφορετικά εμφανιζεται μήνυμα αποτυχιας
            JOptionPane.showMessageDialog(this, "Αποτυχία εύρεσης στατιστικών...", "ΣΦΑΛΜΑ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_viewMonthlyStatsBtnMouseClicked
    
    /**
     * Event handler για την περίπτωση που 
     * ο χρήστης κανει κλικ στο κουμπί "< ΑΡΧΙΚΗ".
     * Κλείνει το τρέχον παράθυρο και εμφανίζει στον χρήστη την αρχική οθόνη.
     */
    private void backToMainBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMainBtnMouseClicked
        firstscreen startscreen = new firstscreen();
        RefineryUtilities.centerFrameOnScreen(startscreen);
        
        setVisible(false);
        dispose();
        
        startscreen.setVisible(true);
    }//GEN-LAST:event_backToMainBtnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JButton viewMonthlyStatsBtn;
    private javax.swing.JComboBox<String> yearForMonthlyStats;
    // End of variables declaration//GEN-END:variables
}
