CREATE TABLE WINNINGNUMBERS(
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    LIST BLOB(2147483647) NOT NULL,
    BONUS BLOB(2147483647) NOT NULL
);

CREATE TABLE DRAW (
    DRAWID INTEGER NOT NULL PRIMARY KEY,
    DRAWTIME BIGINT NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    WINNINGNUMBERS_ID INTEGER,
    CONSTRAINT DRAWWINNUM_FK FOREIGN KEY (WINNINGNUMBERS_ID) REFERENCES WINNINGNUMBERS(ID)
);

CREATE TABLE PRIZECATEGORY (
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CATEGORYTYPE VARCHAR(255) NOT NULL,
    DISTRIBUTED DOUBLE,
    DIVIDENT DOUBLE,
    JACKPOT DOUBLE,
    WINNERS INTEGER,
    DRAW_ID INTEGER,
    CONSTRAINT DRAWPRZCTGRY_FK FOREIGN KEY (DRAW_ID) REFERENCES DRAW(DRAWID)
);